# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sum = 0
k = [1,1]
j = 0

while j < 4000000:
	if k[1] % 2 == 0:
		sum += k[1]

	k1 = k[1]
	k[1] = k[0] + k[1]
	k[0] = k1
	j = k[1]

print (sum)